db = "/usr/src/app/strfry-db/"

relay {
    bind = "0.0.0.0"
    port = 7777

    nofiles = 0

    info {
        name = "FIPS NAT Lab Relay"
        description = "Local relay for Docker NAT traversal tests."
        pubkey = ""
        contact = ""
    }

    maxWebsocketPayloadSize = 131072
    autoPingSeconds = 30
    enableTcpNoDelay = true
    rejectFutureEventsSeconds = 60
    rejectEphemeralEventsOlderThanSeconds = 60
    rejectEventsNewerThanSeconds = 60
    maxFilterLimit = 500
    maxSubsPerConnection = 50

    writePolicy {
        plugin = ""
    }

    compression {
        enabled = true
        slidingWindow = true
    }
}
